/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dtw_asr_CallUtils */

#ifndef _Included_com_dtw_asr_CallUtils
#define _Included_com_dtw_asr_CallUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dtw_asr_CallUtils
 * Method:    callSimpleInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dtw_1asr_CallUtils_callSimpleInfo
  (JNIEnv *, jclass);
JNIEXPORT jobjectArray JNICALL Java_com_dtw_1asr_CallUtils_getMfcc
  (JNIEnv *, jclass, jshortArray);
#ifdef __cplusplus
}
#endif
#endif
