/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <com_dtw_asr_CallUtils.h>
#include <mfcc.h>
#include  <malloc.h>
#include <math.h>

#include <android/log.h>

#define LOG_TAG "-------lin---------"
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG,LOG_TAG,__VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,LOG_TAG,__VA_ARGS__)


/* Header for class com_dtw_asr_CallUtils */

/*
 * Class:     com_dtw_asr_CallUtils
 * Method:    callSimpleInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dtw_1asr_CallUtils_callSimpleInfo
  (JNIEnv *env, jclass ojb){


  return (*env) -> NewStringUTF(env,"Hello, I'm an info come from use ndk-build");

}

JNIEXPORT jobjectArray JNICALL Java_com_dtw_1asr_CallUtils_getMfcc
  (JNIEnv *env, jclass obj, jshortArray Attr){

        int samples =(*env)->GetArrayLength(env,Attr);
        short *tmp  =  (short*)malloc(samples*sizeof(short));
    	(*env)->GetShortArrayRegion(env,Attr,0,samples,tmp);

    	float *data = (float*)malloc(samples * sizeof(float));
    	for(int i = 0; i < samples; i++)
        		{
        			data[i] = (float)tmp[i]/(32768.0);
        		}
			int sample_rate=16000;
			int frame_len=400;
			int frame_shift=160;
			int numc=12;
			int nfilt=24;
			float preemh=0.9375;
			int nfft=512;

        

        	        //printf("----2");
        	        int nframes = (samples - frame_len)/frame_shift + 1;
//        	        LOGI("nframes=%d",nframes);
        	    	float *zrc = (float*) malloc( sizeof(float)*nframes);
        	    	float *amp = (float*) malloc( sizeof(float)*nframes);
        	    	float amp1 = 10.0;
        	    	float amp2 = 2.0;
        	    	float zrc2 = 5;

        	    	int status=0;
        	    	int count=0;
        	    	int silence=0;
        	    	double maxSilence = 8;
        	    	double minLen= 15;

        	    	float sumAmp =0;

        	    	int start=0;
        	    	int end=0;
        	    	int valid=0;

        	    	for(int j = 0; j <nframes ; j++)//必须按顺序输出，不能直接获取指定帧的mfcc差分
        	    	{
        	    		Vad_zrc_amp_cal(data,frame_len,frame_shift,j+1,zrc+j,amp+j,1);

                        if(sumAmp<amp[j])
                            sumAmp=amp[j];

        	    	}
                    sumAmp/=4;

        	    	amp1=(amp1<sumAmp)?sumAmp:amp1;
        	    	amp2=2;//(amp2<sumAmp/2)?sumAmp/2:amp2;
                    LOGI("amp1=%f",amp1);
//                    LOGI("amp2=%f",amp2);

        	    	for(int i=0;i<nframes;i++){
        	    		switch(status){
        	    		case 0:
        	    		case 1:
        	    			if(amp[i]>amp1) {
        	    				start = (i-count-1)>0?(i-count-1):0;
//        	    				LOGI("i=%d",i);
//        	    				LOGI("count=%d",count);
        	    				status = 2;
        	    				silence = 0;
        	    				count += 1;
        	    			}
        	    			else if(amp[i] > amp2 || zrc[i] > zrc2) {
        	    				count +=1;
        	    				status = 1;
        	    			}
        	    			else {
        	    				count = 0;
        	    				status = 0;
        	    			}
        	    			break;
        	    		case 2:
        	    			if (amp[i] > amp2 || zrc[i] >zrc2){
        	    				count += 1;
        	    				silence=0;
        	    				}
        	    			else  {
        	    				silence+=1;
        	    				if (silence < maxSilence)
        	    					count += 1;
        	    			    else if( count < minLen) {
        	    			    	status = 0;
        	    			        count = 0;
        	    			        silence = 0;
        	    			    }
        	    			    else
        	    			    	status =3;
        	    			 }
        	    			break;
        	    		case 3:

        	    				valid=1;
        	    			break;
        	    		default:
        	    			status=0;
        	    			count=0;
        	    			silence=0;
        	    			break;
        	    		}

        	    	}
        	        //printf("----4");
        	        if(valid==0){
                       LOGI("no voice");
                       return NULL;
                    }
        	    	count =count - silence/2;
        	    	end =start+count-1;
        	    	end =end>nframes?nframes:end;
                    LOGI("start=%d",start);
        	    	if(start+5>=end){
        	    	    LOGI("----return");
        	    	    return NULL;
        	    	}



				MfccInfo*p=MfccInit( sample_rate, frame_len,frame_shift,numc,nfilt,preemh,nfft );

				Mfcc_Data_Pre(p,data,samples);
       	
        int len = numc * 2;
        float *out = (float*) malloc( sizeof(float)* (len));
        jobjectArray ret;
        int x=end-start+1;
        int y=len;
         LOGI("min x=%d",x);
        jclass floatCls=(*env)->FindClass(env,"[F");
        if(floatCls==NULL){
        LOGI("----null");
            return NULL;
            }
        ret = (*env)->NewObjectArray(env,x,floatCls,NULL);
        LOGI("----5");
        for(int j=0;j<p->out_nframes;j++){
            Mfcc_Frame_diff(p,j,out,p->dct.datalen);
            if(j>=start && j<=end){

                jfloatArray floatArr = (*env)->NewFloatArray(env,y);
                (*env)->SetFloatArrayRegion(env,floatArr,0,y,out);
                (*env)->SetObjectArrayElement(env,ret,j-start,floatArr);
                (*env)->DeleteLocalRef(env,floatArr);
            }

        }
        free(tmp);
        tmp=NULL;
        free(data);
	    data = NULL;
	    free(out);
	    out = NULL;
	    LOGI("----7");
	    MfccDestroy(p);

        return ret;


  }
  
